train:
  _target_: src.datasets.СustomAudioDataset
  audio_size: 8192
  dir: "data/LJSpeech-1.1"
  with_texts: False
  with_audio: True
  limit_to: -1000
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.СustomAudioDataset
  audio_size: 8192
  dir: "data/LJSpeech-1.1"
  with_texts: False
  with_audio: True
  limit_from: -1000
  instance_transforms: ${transforms.instance_transforms.inference}
