device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.WVMOS
    device: ${metrics.device}
    name: "WVMOS"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.WVMOS
    device: ${metrics.device}
    name: "WVMOS"
